import Head from "next/head";
import HomeComponent from "../../components/home/HomeComponent";

const Home = () => {
    return ( 
        <div>
            <Head>
                <title>Next | Home</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/assets/img/blue.svg" />
            </Head>
            <HomeComponent/>
            
        </div>
     );
}
 
export default Home;